### ISSUE TITLE
Question about the -o <offset> option in download

### ISSUE THREAD

**Issue by TristanThrush** [oscar-corpus/ungoliant#63]
Hey there, this is a fantastic codebase! I just have a quick question about the -o option. It could be more of a question about common crawl itself. Here it is:

Is the content of common crawl files uniformly random? So, for example, if I specify -o=79,900, will the 100 files that are downloaded contain a uniformly random sample of the pages from the whole 80,000 files? 

Thanks for any help you can give!

**Comment by Uinelj** [comment]
Hello! 

The answer may lie in the documentation/code of CommonCrawl tools, and their [Apache Nutch fork](https://github.com/commoncrawl/nutch) might be a good entrypoint. I also think that the organization has a [Google Groups](https://groups.google.com/g/common-crawl) where you could get a response. 

Our `-o <offset>` option is really an offset rather than a range: it will skip `offset` shards from the provided `wet.paths` and then download them. It can be useful when your downloading job gets interrupted, but it's not really flexible. We could improve the behaviour of this option.

Let me know if you need anything else :)
